### ISSUE TITLE
No module named DDPG

### ISSUE THREAD

**Issue by Alex-zhai** [MOCR/DDPG#1]
I followed your instructions to install DDPG, but I always get the result of "No module named ddpg"
/home/alex-zhai/Pictures/Screenshot from 2016-05-30 19:35:06.png

Can you tell me your installtion？ Thank you!!

**Comment by MOCR** [comment]
Can't see your picture, but what do you get when you type in a shell `echo $PYTHONPATH` ?

**Comment by Alex-zhai** [comment]
/home/alex-zhai/Downloads:/home/alex-zhai/Downloads/DDPG-master

**Comment by MOCR** [comment]
Ok, is DDPG-master the root directory of the module? if so, rename it DDPG, the name of the module in python is the name of it's root directory, after that you should be able to import it... And the `/home/alex-zhai/Downloads/DDPG-master` path is not usefull in PYTHONPATH, only the directory containing the module is important. Also I hope you have the path to standard python modules in PYTHONPATH and you just cut it out, no?

**Comment by Alex-zhai** [comment]
Everything is OK now. Thank you!

**Comment by MOCR** [comment]
Glad I could help, do not hesitate to leave comments on the code here as it is still a work in progress!

**Comment by Alex-zhai** [comment]
No problem, thank you!
